---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: search
spec:
  version: 7.11.1
  elasticsearchRef:
    name: search
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
# ingress w/ edge termination
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-search
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: search.brxblx.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: search-kb-http
                port:
                  number: 5601
  tls:
    - secretName: search-tls
      hosts:
        - search.brxblx.io