#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: elastic
#spec:
#  destination:
#    name: in-cluster
#    namespace: elastic-system
#  project: default
#  source:
#    repoURL: https://github.com/hfuss/ethernetes
#    path: gitops/deploys/elastic
#    targetRevision: main
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
