apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miner
spec:
  destination:
    name: in-cluster
    namespace: ethereum
  project: default
  source:
    repoURL: https://github.com/hfuss/ethernetes
    path: charts/miner
    targetRevision: main
    helm:
      values: |
        statefulset:
          enabled: false

        extendeddaemonset:
          enabled: true
          settings:
            - name: brx-01a
              nodeSelector:
                kubernetes.io/hostname: brx-01a
              gpus: 2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
