apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-stage-issuer-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudDNS:
            project: ethernetes
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
