apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: search
spec:
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  version: 7.11.1
