apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quorum
spec:
  project: default
  source:
    repoURL: https://github.com/hfuss/quorum-on-k8s
    targetRevision: main
    path: charts/quorum
    helm:
      values: |
        longhornStorageEnabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ethereum
  syncPolicy: {}