apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.2.0
    helm:
      values: |
        installCRDs: true
        extraArgs:
          - '--dns01-recursive-nameservers-only'
          - '--dns01-recursive-nameservers="8.8.8.8:53,1.1.1.1:53"'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
