apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/gpu-operator
    chart: gpu-operator
    targetRevision: '1.5.2'
    helm:
      version: v3
      values: |
        operator:
          defaultRuntime: containerd

        driver:
          repository: ghcr.io/hfuss/nvidia-driver
          version: v0.1.0-f1a2b0c
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: e8s-system
  syncPolicy: {}