name: "Miner Image / CI"
on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'miner/*'
      - .github/workflows/miner-image-build.yml
  push:
    branches:
      - main
    paths:
      - 'miner/*'
      - .github/workflows/miner-image-build.yml
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build
    outputs:
      git-tag: ${{ steps.versions.outputs.git-tag }}
      version: ${{ steps.versions.outputs.version }}
      dirty-version: ${{ steps.versions.outputs.dirty-version }}
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: extract versions
        id: versions
        run: |
          version=$(cat VERSION)
          echo "::set-output name=git-tag::miner-v${version}"
          echo "::set-output name=version::v${version}"
          echo "::set-output name=dirty-version::v${version}-$(git rev-parse --short HEAD)"
        working-directory: miner

      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: hfuss
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: build and test
        run: |
          docker build . -t ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }}
          docker run -i ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }} 'ethminer --help'
          docker push ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }}
        working-directory: miner

  release:
    name: Release
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: enforce new version
        run: |
          ! git rev-parse ${{ needs.build.outputs.git-tag }}

      - name: enforce changelog
        uses: dangoslen/changelog-enforcer@v2
        with:
          changeLogPath: 'miner/CHANGELOG.md'
          skipLabels: 'Skip-Changelog'
          expectedLatestVersion: ${{ needs.build.outputs.version }}

      - name: docker login
        if: ${{ github.event == 'push' }}
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: hfuss
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: promote images
        if: ${{ github.event == 'push' }}
        run: |
          docker tag ghcr.io/hfuss/miner:${{ needs.build.outputs.dirty-version }} ghcr.io/hfuss/miner:${{ needs.build.outputs.version }}
          docker tag ghcr.io/hfuss/miner:${{ needs.build.outputs.dirty-version }} ghcr.io/hfuss/miner:latest
          docker push ghcr.io/hfuss/miner:${{ needs.build.outputs.version }}
          docker push ghcr.io/hfuss/miner:latest

      - name: extract changelog
        id: changelog_reader
        if: ${{ github.event == 'push' }}
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ needs.Build.outputs.version }}
          path: miner/CHANGELOG.md

      - name: git release
        if: ${{ github.event == 'push' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.build.outputs.git-tag }}
          release_name: Miner Image Release ${{ needs.build.outputs.git-tag }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: true
