name: "Miner Image"
on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'miner/*'
      - .github/workflows/miner-image-build.yml
  push:
    branches:
      - main
    paths:
      - 'miner/*'
      - .github/workflows/miner-image-build.yml
jobs:
  ci:
    runs-on: ubuntu-18.04
    name: CI
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: extract versions
        id: versions
        run: |
          version=$(cat VERSION)
          echo "::set-output name=git-tag::miner-v${version}"
          echo "::set-output name=version::v${version}"
          echo "::set-output name=dirty-version::v${version}-$(git rev-parse --short HEAD)"
        working-directory: miner

      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: hfuss
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: build and test
        run: |
          docker build . -t ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }}
          docker run -i ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }} 'ethminer --help'
          docker push ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }}
        working-directory: miner

      - name: enforce new version
        run: |
          ! git rev-parse ${{ steps.versions.outputs.git-tag }}

      - name: enforce changelog
        if: ${{ github.event == 'pull_request' }}
        uses: dangoslen/changelog-enforcer@v2
        with:
          changeLogPath: 'miner/CHANGELOG.md'
          skipLabels: 'Skip-Changelog'
          expectedLatestVersion: ${{ steps.versions.outputs.version }}

      - name: extract changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.versions.outputs.version }}
          path: miner/CHANGELOG.md

      - name: tag images
        run: |
          docker tag ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }} ghcr.io/hfuss/miner:${{ steps.versions.outputs.version }}
          docker tag ghcr.io/hfuss/miner:${{ steps.versions.outputs.dirty-version }} ghcr.io/hfuss/miner:latest

      - name: promote images
        if: ${{ github.event == 'push' }}
        run: |
          docker push ghcr.io/hfuss/miner:${{ steps.versions.outputs.version }}
          docker push ghcr.io/hfuss/miner:latest

      - name: git release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.versions.outputs.git-tag }}
          release_name: Miner Image ${{ steps.versions.outputs.version }} Release
          body: ${{ steps.changelog.outputs.changes }}
          draft: ${{ github.event != 'push' }}
          prerelease: true
