{{- $rootRef := . }}
{{- if and .Values.extendeddaemonset.enabled (not .Values.statefulset.enabled) }}
---
apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: {{ include "miner.fullname" . }}
  labels:
    {{- include "miner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "miner.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "miner.fullname" . }}
  strategy:
    canary:
      replicas: 1
      duration: 3m
      autoPause:
        enabled: true
        maxRestarts: 3
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "miner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "miner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --report-hashrate
            - --syslog
            - --exit
            {{- if .Values.extraArgs }}
            {{- toYaml .Values.extraArgs | nindent 12 }}
            {{- end }}
          env:
            - name: MINING_POOLS
              value: {{ .Values.miningPools | join " " | quote }}
          ports:
            - name: jsonrpc
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: jsonrpc
          readinessProbe:
            tcpSocket:
              port: jsonrpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        nvidia.com/gpu.present: "true"
      {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ range .Values.extendeddaemonset.settings }}
---
apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonsetSetting
metadata:
  name: {{ include "miner.fullname" $rootRef }}-{{ .name }}
  labels:
    {{- include "miner.labels" $rootRef  | nindent 4 }}
spec:
  nodeSelector:
    {{ toYaml .nodeSelector | nindent 4 }}
  reference:
    kind: ExtendedDaemonSet
    name: {{ include "miner.fullname" $rootRef | quote }}
  containers:
    - name: miner
      resources:
        limits:
          nvidia.com/gpu: {{ .gpus }}
{{- end }}
{{- end }}
